import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Smartt App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen">
        {/* Sidebar can be added here later if needed */}
        <div className="flex-1 flex flex-col">
          {/* Navbar can be added here too */}
          <main className="h-full min-h-[1026px] bg-[#ffffff] flex-1">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
