import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/Context/AuthContext";

export const metadata: Metadata = {
  title: "Smartt App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen">
        <div className="flex-1 flex flex-col">
          <main className="h-full md:min-h-[1026px] bg-[#ffffff] flex-1">
            <AuthProvider>
              {children}
            </AuthProvider>
          </main>
        </div>
      </body>
    </html>
  );
}
